"""C2 Source Registry, Inventory Snapshot, and Freshness model."""

from flowguard_models.harness import CaseRule, FiniteModelSpec, HazardSpec


SPEC = FiniteModelSpec(
    model_id="C2_source_registry",
    title="C2 Source Registry, Inventory & Freshness",
    modeled_boundary=(
        "immutable occurrence/source identity, inventory snapshots, change "
        "sets, versioning, safe visual derivatives, freshness invalidation, "
        "no-delta, and tombstones"
    ),
    state_fields=(
        "source.identity",
        "source.version",
        "source.content_hash",
        "source.metadata_hash",
        "source.tombstone",
        "visual_asset.identity",
        "visual_asset.derivative_revision",
        "visual_asset.renderer_identity",
        "visual_asset.safety_disposition",
        "inventory.snapshot_revision",
        "inventory.change_set",
        "dependency.freshness",
    ),
    owned_write_fields=(
        "source.identity",
        "source.version",
        "source.content_hash",
        "source.metadata_hash",
        "source.tombstone",
        "visual_asset.identity",
        "visual_asset.derivative_revision",
        "visual_asset.renderer_identity",
        "visual_asset.safety_disposition",
        "inventory.snapshot_revision",
        "inventory.change_set",
        "dependency.freshness",
    ),
    side_effect_classes=(
        "source_registry_write",
        "inventory_snapshot_write",
        "freshness_invalidation_write",
    ),
    completion_evidence=(
        "SourceVersion",
        "MetadataRevision",
        "InventorySnapshot",
        "ChangeSet",
        "Added",
        "Modified",
        "Moved",
        "Deleted",
        "NewlyReachable",
        "NoDelta",
        "Tombstone",
        "InvalidationRequest",
        "VisualDerivative",
        "VisualSafetyDisposition",
    ),
    rules=(
        CaseRule(
            case_id="inventory_first_snapshot",
            decision="inventory_snapshot_created",
            label="inventory_snapshot_created",
            writes=("inventory.snapshot_revision", "inventory.change_set"),
            side_effects=("inventory_snapshot_write",),
            emitted_tokens=("InventorySnapshot", "ChangeSet", "Added"),
            reason="the first bounded enumeration records stable occurrences without claiming content ingestion",
        ),
        CaseRule(
            case_id="new_content",
            decision="source_version_created",
            label="source_version_created",
            writes=(
                "source.identity",
                "source.version",
                "source.content_hash",
                "source.metadata_hash",
            ),
            side_effects=("source_registry_write",),
            emitted_tokens=("SourceVersion",),
            reason="new stable content creates an immutable version",
        ),
        CaseRule(
            case_id="metadata_only_change",
            decision="metadata_revision_created",
            label="metadata_revision_created",
            writes=("source.version", "source.metadata_hash"),
            side_effects=("source_registry_write",),
            emitted_tokens=("MetadataRevision", "Modified"),
            reason="metadata identity changes without pretending content changed",
        ),
        CaseRule(
            case_id="occurrence_moved_same_content",
            decision="move_recorded_dependents_reviewed",
            label="move_recorded_dependents_reviewed",
            writes=("inventory.snapshot_revision", "inventory.change_set", "dependency.freshness"),
            side_effects=("inventory_snapshot_write", "freshness_invalidation_write"),
            emitted_tokens=("InventorySnapshot", "ChangeSet", "Moved", "InvalidationRequest"),
            reason="move preserves content identity while location/policy dependents are re-evaluated",
        ),
        CaseRule(
            case_id="occurrence_newly_reachable",
            decision="newly_reachable_recorded",
            label="newly_reachable_recorded",
            writes=("inventory.snapshot_revision", "inventory.change_set", "dependency.freshness"),
            side_effects=("inventory_snapshot_write", "freshness_invalidation_write"),
            emitted_tokens=("InventorySnapshot", "ChangeSet", "NewlyReachable", "InvalidationRequest"),
            reason="hydration or permission change creates a new bounded processing candidate",
        ),
        CaseRule(
            case_id="identical_rescan",
            decision="no_delta",
            label="identical_no_delta",
            emitted_tokens=("NoDelta",),
            reason="an unchanged occurrence and policy produces no duplicate work",
        ),
        CaseRule(
            case_id="source_modified",
            decision="source_version_and_invalidation_created",
            label="source_modified",
            writes=(
                "source.version",
                "source.content_hash",
                "source.metadata_hash",
                "inventory.snapshot_revision",
                "inventory.change_set",
                "dependency.freshness",
            ),
            side_effects=(
                "source_registry_write",
                "inventory_snapshot_write",
                "freshness_invalidation_write",
            ),
            emitted_tokens=("SourceVersion", "ChangeSet", "Modified", "InvalidationRequest"),
            reason="content change stales only the occurrence and declared dependents",
        ),
        CaseRule(
            case_id="source_deleted",
            decision="tombstone_and_invalidation_created",
            label="tombstone_created",
            writes=(
                "source.version",
                "source.tombstone",
                "inventory.snapshot_revision",
                "inventory.change_set",
                "dependency.freshness",
            ),
            side_effects=(
                "source_registry_write",
                "inventory_snapshot_write",
                "freshness_invalidation_write",
            ),
            emitted_tokens=("Tombstone", "Deleted", "ChangeSet", "InvalidationRequest"),
            reason="confirmed deletion creates a tombstone and stales declared dependents",
        ),
        CaseRule(
            case_id="eligible_visual_derivative",
            decision="safe_visual_derivative_created",
            label="safe_visual_derivative_created",
            writes=(
                "visual_asset.identity",
                "visual_asset.derivative_revision",
                "visual_asset.renderer_identity",
                "visual_asset.safety_disposition",
                "dependency.freshness",
            ),
            side_effects=("source_registry_write", "freshness_invalidation_write"),
            emitted_tokens=("VisualDerivative", "VisualSafetyDisposition"),
            reason=(
                "an allowlisted image or supported document region is rendered "
                "locally with macros, network, and external content disabled"
            ),
        ),
        CaseRule(
            case_id="unsafe_or_stale_visual",
            decision="visual_derivative_unavailable",
            label="visual_derivative_unavailable",
            writes=("visual_asset.safety_disposition", "dependency.freshness"),
            side_effects=("freshness_invalidation_write",),
            emitted_tokens=("VisualSafetyDisposition", "InvalidationRequest"),
            reason=(
                "unsafe, denied, unreadable, unsupported, or stale visual content "
                "is terminally unavailable and cannot become a card cover"
            ),
        ),
        CaseRule(
            case_id="ai_rewrite_attempt",
            decision="source_mutation_rejected",
            label="source_mutation_rejected",
            emitted_tokens=("SourceMutationRejected",),
            reason="AI-authored replacement cannot mutate original source content",
        ),
    ),
    hazards=(
        HazardSpec(
            failure_id="H-C2-001-ai-rewrites-original",
            protected_error_class="source_truth_mutation",
            description="AI-authored text replaces provider source content",
            protected_harm="the provenance record no longer represents the source",
            case_id="ai_rewrite_attempt",
            broken_decision="source_version_created",
            broken_writes=("source.version", "source.content_hash", "source.metadata_hash"),
            broken_side_effects=("source_registry_write",),
            broken_tokens=("SourceVersion",),
        ),
        HazardSpec(
            failure_id="H-C2-002-rescan-duplicates-work",
            protected_error_class="duplicate_side_effect",
            description="an unchanged rescan writes another snapshot or source version",
            protected_harm="background scanning creates duplicate analysis and unstable counts",
            case_id="inventory_first_snapshot",
            broken_decision="inventory_snapshot_created",
            broken_writes=("inventory.snapshot_revision", "inventory.change_set"),
            broken_side_effects=("inventory_snapshot_write",),
            broken_tokens=("InventorySnapshot", "ChangeSet", "Added"),
            ignore_idempotency=True,
        ),
        HazardSpec(
            failure_id="H-C2-003-metadata-becomes-content",
            protected_error_class="hash_identity_conflation",
            description="a metadata-only change is recorded as a content change",
            protected_harm="downstream evidence is invalidated against the wrong identity",
            case_id="metadata_only_change",
            broken_decision="source_version_created",
            broken_writes=("source.version", "source.content_hash", "source.metadata_hash"),
            broken_side_effects=("source_registry_write",),
            broken_tokens=("SourceVersion",),
        ),
        HazardSpec(
            failure_id="H-C2-004-change-keeps-dependents-current",
            protected_error_class="freshness_propagation_loss",
            description="modified content does not stale declared dependents",
            protected_harm="old triage, anchors, analysis, and projections look current",
            case_id="source_modified",
            broken_decision="source_version_created",
            broken_writes=("source.version", "source.content_hash", "source.metadata_hash"),
            broken_side_effects=("source_registry_write",),
            broken_tokens=("SourceVersion",),
        ),
        HazardSpec(
            failure_id="H-C2-005-deletion-without-tombstone",
            protected_error_class="deletion_propagation_loss",
            description="a deleted source disappears without a tombstone or invalidation",
            protected_harm="dependents remain current after their source was deleted",
            case_id="source_deleted",
            broken_decision="no_delta",
            broken_tokens=("NoDelta",),
        ),
        HazardSpec(
            failure_id="H-C2-007-unsafe-visual-rendered",
            protected_error_class="visual_derivative_safety_escape",
            description="an unsafe or stale source is rendered as a current visual derivative",
            protected_harm="active or unrelated private content becomes a card image",
            case_id="unsafe_or_stale_visual",
            broken_decision="safe_visual_derivative_created",
            broken_writes=(
                "visual_asset.identity",
                "visual_asset.derivative_revision",
                "visual_asset.safety_disposition",
            ),
            broken_tokens=("VisualDerivative",),
        ),
        HazardSpec(
            failure_id="H-C2-006-move-creates-unrelated-content",
            protected_error_class="occurrence_content_identity_collapse",
            description="a move is treated as unrelated new content without identity reconciliation",
            protected_harm="duplicates and broken history replace a continuous source occurrence",
            case_id="occurrence_moved_same_content",
            broken_decision="source_version_created",
            broken_writes=("source.identity", "source.version", "source.content_hash"),
            broken_side_effects=("source_registry_write",),
            broken_tokens=("SourceVersion",),
        ),
    ),
    risk_classes=(
        "deduplication",
        "idempotency",
        "freshness",
        "side_effect",
        "provenance",
    ),
    template_ids=("side_effect_at_most_once",),
    blindspots=(
        "real provider occurrence stability requires adapter conformance",
        "rename identity thresholds and cloud hydration require source-type tests",
        "durable transaction and restart behavior require runtime evidence",
    ),
    claim_boundary=(
        "This model establishes bounded C2 inventory, change-set, source-version, "
        "freshness, safe visual-derivative, no-delta, and tombstone behavior. It does not prove durable "
        "storage, provider enumeration completeness, or real dependency execution."
    ),
)
