"""C10 Correction, Invalidation, Original-Owner Recompute, and Recovery model."""

from flowguard_models.harness import CaseRule, FiniteModelSpec, HazardSpec


SPEC = FiniteModelSpec(
    model_id="C10_correction_revocation",
    title="C10 Correction, Invalidation & Recompute",
    modeled_boundary=(
        "append-only correction/revocation/deletion, dependency-graph "
        "invalidation, original-owner dispatch, terminal join, retry, restart, "
        "and optional representative-visual pin/unpin/change-cover correction"
    ),
    state_fields=(
        "revision_graph",
        "invalidation_plan",
        "recompute_request",
        "recompute.owner_dispositions",
        "recompute.join_status",
        "recompute.checkpoint",
        "correction.card_visual_intent",
    ),
    owned_write_fields=(
        "revision_graph",
        "invalidation_plan",
        "recompute_request",
        "recompute.owner_dispositions",
        "recompute.join_status",
        "recompute.checkpoint",
        "correction.card_visual_intent",
    ),
    side_effect_classes=(
        "append_revision",
        "dispatch_recompute_request",
        "append_owner_disposition",
        "append_recompute_checkpoint",
    ),
    completion_evidence=(
        "RevisionGraph",
        "InvalidationPlan",
        "RecomputeRequest",
        "DependentDisposition",
        "OwnerTerminalSet",
        "RecomputeJoinCurrent",
        "RecomputeBlocked",
        "RecoveryCheckpoint",
        "CardVisualCorrection",
    ),
    rules=(
        CaseRule(
            case_id="user_correction",
            decision="correction_appended_and_recompute_requested",
            label="correction_appended",
            writes=("revision_graph", "invalidation_plan", "recompute_request", "recompute.checkpoint"),
            side_effects=("append_revision", "dispatch_recompute_request", "append_recompute_checkpoint"),
            emitted_tokens=("RevisionGraph", "InvalidationPlan", "RecomputeRequest", "RecoveryCheckpoint"),
            reason="correction preserves history and dispatches affected original owners",
        ),
        CaseRule(
            case_id="card_visual_pin_unpin_or_change",
            decision="card_visual_correction_appended",
            label="card_visual_correction_appended",
            writes=(
                "revision_graph",
                "invalidation_plan",
                "recompute_request",
                "recompute.checkpoint",
                "correction.card_visual_intent",
            ),
            side_effects=(
                "append_revision",
                "dispatch_recompute_request",
                "append_recompute_checkpoint",
            ),
            emitted_tokens=(
                "RevisionGraph",
                "InvalidationPlan",
                "RecomputeRequest",
                "RecoveryCheckpoint",
                "CardVisualCorrection",
            ),
            reason=(
                "pin, unpin, hide, or change-cover is an optional append-only "
                "correction that re-enters C12 after visual invalidation"
            ),
        ),
        CaseRule(
            case_id="source_or_tracking_stale",
            decision="all_dependents_disposed",
            label="all_dependents_disposed",
            writes=("invalidation_plan", "recompute_request", "recompute.owner_dispositions"),
            side_effects=("dispatch_recompute_request", "append_owner_disposition"),
            emitted_tokens=("InvalidationPlan", "DependentDisposition", "RecomputeRequest"),
            reason="every exact dependent receives recompute, remove, retain, review, or blocked disposition",
        ),
        CaseRule(
            case_id="all_required_owners_terminal",
            decision="recompute_join_current",
            label="recompute_join_current",
            writes=("recompute.owner_dispositions", "recompute.join_status", "recompute.checkpoint"),
            side_effects=("append_owner_disposition", "append_recompute_checkpoint"),
            emitted_tokens=("OwnerTerminalSet", "RecomputeJoinCurrent", "RecoveryCheckpoint"),
            reason="every dependency-graph owner is terminal for the same input revision",
        ),
        CaseRule(
            case_id="required_owner_failed_or_missing",
            decision="recompute_join_blocked",
            label="recompute_join_blocked",
            writes=("recompute.owner_dispositions", "recompute.join_status", "recompute.checkpoint"),
            side_effects=("append_owner_disposition", "append_recompute_checkpoint"),
            emitted_tokens=("RecomputeBlocked", "RecoveryCheckpoint"),
            reason="failed, stale, or missing owner disposition blocks fresh projection",
        ),
        CaseRule(
            case_id="restart_with_current_checkpoint",
            decision="recompute_resumed",
            label="recompute_resumed",
            writes=("recompute_request", "recompute.checkpoint"),
            side_effects=("dispatch_recompute_request", "append_recompute_checkpoint"),
            emitted_tokens=("RecomputeRequest", "RecoveryCheckpoint"),
            reason="restart resumes only missing owners after authorization and freshness revalidation",
        ),
        CaseRule(
            case_id="authorization_revoked",
            decision="revocation_appended_and_dependents_invalidated",
            label="revocation_appended",
            writes=("revision_graph", "invalidation_plan", "recompute_request", "recompute.checkpoint"),
            side_effects=("append_revision", "dispatch_recompute_request", "append_recompute_checkpoint"),
            emitted_tokens=("Revoked", "InvalidationPlan", "RecomputeRequest", "RecoveryCheckpoint"),
            reason="revocation stops reads and invalidates derived state",
        ),
        CaseRule(
            case_id="ui_only_patch_request",
            decision="ui_only_patch_rejected",
            label="ui_only_patch_rejected",
            emitted_tokens=("CorrectionRejected",),
            reason="correction cannot change only the projection",
        ),
        CaseRule(
            case_id="direct_foreign_state_write",
            decision="foreign_state_write_rejected",
            label="foreign_state_write_rejected",
            emitted_tokens=("OwnerWriteRejected",),
            reason="C10 requests recompute and never writes another owner field",
        ),
    ),
    hazards=(
        HazardSpec(
            failure_id="H-C10-001-correction-overwrites-history",
            protected_error_class="revision_history_loss",
            description="a correction overwrites the prior canonical revision",
            protected_harm="the user cannot reconstruct why an earlier decision was visible",
            case_id="user_correction",
            broken_decision="correction_overwritten",
            broken_writes=("revision_graph",),
            broken_side_effects=("append_revision",),
            broken_tokens=("CurrentRevisionOnly",),
        ),
        HazardSpec(
            failure_id="H-C10-002-dependent-omitted",
            protected_error_class="invalidation_propagation_gap",
            description="one dependency-graph owner receives no disposition",
            protected_harm="stale evidence or projections remain current",
            case_id="source_or_tracking_stale",
            broken_decision="partial_dependents_disposed",
            broken_writes=("invalidation_plan", "recompute.owner_dispositions"),
            broken_side_effects=("append_owner_disposition",),
            broken_tokens=("DependentDisposition",),
        ),
        HazardSpec(
            failure_id="H-C10-003-early-join",
            protected_error_class="nonterminal_owner_join",
            description="recompute is declared current with a missing or failed owner",
            protected_harm="C12 publishes a fresh-looking projection over stale dependencies",
            case_id="required_owner_failed_or_missing",
            broken_decision="recompute_join_current",
            broken_writes=("recompute.join_status",),
            broken_tokens=("RecomputeJoinCurrent",),
        ),
        HazardSpec(
            failure_id="H-C10-004-restart-duplicates-owner-work",
            protected_error_class="recompute_retry_duplication",
            description="restart redispatches already terminal owners and duplicates revisions",
            protected_harm="correction history and projections diverge after recovery",
            case_id="restart_with_current_checkpoint",
            broken_decision="recompute_resumed",
            broken_writes=("recompute_request", "recompute.checkpoint"),
            broken_side_effects=("dispatch_recompute_request", "append_recompute_checkpoint"),
            broken_tokens=("RecomputeRequest", "RecoveryCheckpoint"),
            ignore_idempotency=True,
        ),
        HazardSpec(
            failure_id="H-C10-005-ui-only-correction",
            protected_error_class="projection_only_correction",
            description="a user correction changes only the UI",
            protected_harm="the canonical decision and other projections remain wrong",
            case_id="ui_only_patch_request",
            broken_decision="ui_projection_patched",
            broken_tokens=("ProjectionUpdated",),
        ),
        HazardSpec(
            failure_id="H-C10-007-cover-change-patches-ui-only",
            protected_error_class="card_visual_correction_bypass",
            description="a cover change patches the browser without revision and invalidation",
            protected_harm="restart or rescan silently restores a stale representative image",
            case_id="card_visual_pin_unpin_or_change",
            broken_decision="ui_projection_patched",
            broken_writes=("correction.card_visual_intent",),
            broken_tokens=("CardVisualCorrection",),
        ),
        HazardSpec(
            failure_id="H-C10-006-c10-writes-child-state",
            protected_error_class="foreign_writer_escape",
            description="C10 directly writes another owner canonical field",
            protected_harm="correction coordination becomes a second authority",
            case_id="direct_foreign_state_write",
            broken_decision="lifecycle_state_written",
            broken_writes=("matter.lifecycle_axes",),
            broken_tokens=("LifecycleState",),
        ),
    ),
    risk_classes=(
        "state_transition",
        "ownership",
        "idempotency",
        "freshness",
        "recovery",
        "side_effect",
    ),
    template_ids=("side_effect_at_most_once",),
    blindspots=(
        "dependency graph construction requires implementation conformance",
        "real owner executors and durable restart require runtime evidence",
        "physical deletion and retention policy remain separate",
    ),
    claim_boundary=(
        "This model establishes bounded C10 append-only history, exact "
        "invalidation, original-owner terminal joins, retry, restart, and "
        "foreign-writer rejection. It does not prove the production dependency "
        "graph, durable execution, or C12 publication conformance."
    ),
)
