"""M0 autonomous end-to-end authority and coverage-ledger model."""

from flowguard_models.harness import CaseRule, FiniteModelSpec, HazardSpec


SPEC = FiniteModelSpec(
    model_id="M0_matters_end_to_end_authority",
    title="M0 Autonomous Matters End-to-End Authority",
    modeled_boundary=(
        "one orchestration snapshot over current C1-C12 source-universe, "
        "ObjectCoverageLedger, freshness, semantic depth, automatic original-owner "
        "dispatch, visual/localization/UI readiness, retry/restart recovery, "
        "ResearchGuard release gating, and unconsumed-output obligations"
    ),
    state_fields=(
        "orchestration.child_receipt_set",
        "orchestration.integration_status",
        "orchestration.object_coverage_ledger_revision",
        "orchestration.object_stage_terminal_index",
        "orchestration.registered_object_count",
        "orchestration.ui_ready_object_count",
        "orchestration.blocked_object_count",
        "orchestration.worker_checkpoint",
        "orchestration.worker_health",
        "orchestration.work_item_registry",
        "orchestration.coverage_status",
        "orchestration.depth_status",
        "orchestration.research_status",
        "orchestration.analysis_status",
    ),
    owned_write_fields=(
        "orchestration.child_receipt_set",
        "orchestration.integration_status",
        "orchestration.object_coverage_ledger_revision",
        "orchestration.object_stage_terminal_index",
        "orchestration.registered_object_count",
        "orchestration.ui_ready_object_count",
        "orchestration.blocked_object_count",
        "orchestration.worker_checkpoint",
        "orchestration.worker_health",
        "orchestration.work_item_registry",
        "orchestration.coverage_status",
        "orchestration.depth_status",
        "orchestration.research_status",
        "orchestration.analysis_status",
    ),
    side_effect_classes=(
        "orchestration_receipt_write",
        "coverage_ledger_write",
        "work_dispatch_write",
        "worker_checkpoint_write",
    ),
    completion_evidence=(
        "CurrentChildReceiptSet",
        "ConsumedOutputInventory",
        "ObjectCoverageLedgerCurrent",
        "AllRegisteredObjectsTerminal",
        "AllAdmittedMattersUIReady",
        "M0IntegrationReceipt",
        "SourceUniverseTerminal",
        "DepthCurrent",
        "ResearchCurrent",
        "AnalysisTerminal",
        "OriginalOwnerTerminalSet",
        "WorkerCheckpoint",
    ),
    rules=(
        CaseRule(
            case_id="all_registered_objects_terminal_and_ui_ready",
            decision="end_to_end_current",
            label="end_to_end_current",
            writes=(
                "orchestration.child_receipt_set",
                "orchestration.integration_status",
                "orchestration.object_coverage_ledger_revision",
                "orchestration.object_stage_terminal_index",
                "orchestration.registered_object_count",
                "orchestration.ui_ready_object_count",
                "orchestration.blocked_object_count",
                "orchestration.worker_checkpoint",
                "orchestration.worker_health",
                "orchestration.work_item_registry",
                "orchestration.coverage_status",
                "orchestration.depth_status",
                "orchestration.research_status",
                "orchestration.analysis_status",
            ),
            side_effects=(
                "orchestration_receipt_write",
                "coverage_ledger_write",
                "worker_checkpoint_write",
            ),
            emitted_tokens=(
                "CurrentChildReceiptSet",
                "ConsumedOutputInventory",
                "ObjectCoverageLedgerCurrent",
                "AllRegisteredObjectsTerminal",
                "AllAdmittedMattersUIReady",
                "M0IntegrationReceipt",
                "SourceUniverseTerminal",
                "DepthCurrent",
                "ResearchCurrent",
                "AnalysisTerminal",
                "OriginalOwnerTerminalSet",
                "WorkerCheckpoint",
            ),
            reason=(
                "every registered occurrence has a current terminal pointer for "
                "required stages, every admitted Matter has owner decisions, en/"
                "zh-CN values, representative visual or placeholder, and an "
                "openable current C12 projection"
            ),
        ),
        CaseRule(
            case_id="missing_or_stale_stage_work",
            decision="work_scheduled",
            label="work_scheduled",
            writes=(
                "orchestration.integration_status",
                "orchestration.object_stage_terminal_index",
                "orchestration.work_item_registry",
                "orchestration.worker_checkpoint",
            ),
            side_effects=("coverage_ledger_write", "work_dispatch_write", "worker_checkpoint_write"),
            emitted_tokens=("ObjectCoverageLedgerCurrent", "WorkScheduled", "WorkerCheckpoint"),
            reason="missing or stale owner stages are deterministically scheduled without user confirmation",
        ),
        CaseRule(
            case_id="typed_finding_owner_join_pending",
            decision="original_owner_join_required",
            label="original_owner_join_required",
            writes=(
                "orchestration.child_receipt_set",
                "orchestration.integration_status",
                "orchestration.work_item_registry",
            ),
            side_effects=("work_dispatch_write", "orchestration_receipt_write"),
            emitted_tokens=("OriginalOwnerDispatch", "RecomputeRequired"),
            reason="a validated finding cannot reach C12 until its declared owner returns one terminal result",
        ),
        CaseRule(
            case_id="one_object_blocked_others_progress",
            decision="object_blocked_progress_continues",
            label="object_blocked_progress_continues",
            writes=(
                "orchestration.object_stage_terminal_index",
                "orchestration.blocked_object_count",
                "orchestration.integration_status",
            ),
            side_effects=("coverage_ledger_write",),
            emitted_tokens=("ObjectBlocked", "ObjectCoverageLedgerCurrent"),
            reason="one blocked object is terminally visible while unrelated work keeps advancing",
        ),
        CaseRule(
            case_id="progressive_inventory_partial",
            decision="inventory_progress_visible_not_complete",
            label="inventory_progress_visible_not_complete",
            writes=(
                "orchestration.integration_status",
                "orchestration.coverage_status",
                "orchestration.object_coverage_ledger_revision",
            ),
            side_effects=("coverage_ledger_write",),
            emitted_tokens=("CoveragePartial", "ObjectCoverageLedgerCurrent"),
            reason="current partial inventory is visible but cannot support a complete coverage claim",
        ),
        CaseRule(
            case_id="semantic_depth_partial",
            decision="depth_work_scheduled",
            label="depth_work_scheduled",
            writes=(
                "orchestration.integration_status",
                "orchestration.depth_status",
                "orchestration.work_item_registry",
            ),
            side_effects=("work_dispatch_write",),
            emitted_tokens=("DepthWorkScheduled",),
            reason="missing, blocked, or stale depth obligations schedule bounded owner work",
        ),
        CaseRule(
            case_id="visual_localization_or_ui_gap",
            decision="projection_work_scheduled",
            label="projection_work_scheduled",
            writes=(
                "orchestration.integration_status",
                "orchestration.object_stage_terminal_index",
                "orchestration.work_item_registry",
            ),
            side_effects=("coverage_ledger_write", "work_dispatch_write"),
            emitted_tokens=("ProjectionWorkScheduled",),
            reason="admitted Matter lacks current visual, localization, or UI reachability",
        ),
        CaseRule(
            case_id="researchguard_pending",
            decision="research_release_blocked_nonresearch_continues",
            label="research_release_blocked_nonresearch_continues",
            writes=("orchestration.integration_status", "orchestration.research_status"),
            side_effects=("orchestration_receipt_write",),
            emitted_tokens=("ResearchGuardPending", "ReleaseBlocked"),
            reason="non-research autonomous work continues but complete v0.1 release cannot claim research",
        ),
        CaseRule(
            case_id="stale_child_receipt",
            decision="freshness_blocked",
            label="freshness_blocked",
            writes=("orchestration.integration_status", "orchestration.work_item_registry"),
            side_effects=("work_dispatch_write",),
            emitted_tokens=("StaleChildReceipt", "WorkScheduled"),
            reason="a stale child receipt invalidates the parent snapshot and schedules its owner",
        ),
        CaseRule(
            case_id="unconsumed_child_output",
            decision="integration_gap_blocked",
            label="integration_gap_blocked",
            writes=("orchestration.integration_status",),
            side_effects=("orchestration_receipt_write",),
            emitted_tokens=("UnconsumedOutput", "M0BlockedReceipt"),
            reason="every declared child output must have one downstream consumer or typed terminal",
        ),
        CaseRule(
            case_id="correction_invalidates_downstream",
            decision="recompute_scheduled",
            label="recompute_scheduled",
            writes=(
                "orchestration.child_receipt_set",
                "orchestration.integration_status",
                "orchestration.object_stage_terminal_index",
                "orchestration.work_item_registry",
            ),
            side_effects=("coverage_ledger_write", "work_dispatch_write"),
            emitted_tokens=("InvalidatedChildReceipts", "RecomputeRequired"),
            reason="optional correction or revocation invalidates and schedules exact affected owners",
        ),
        CaseRule(
            case_id="restart_from_checkpoint",
            decision="worker_resumed_missing_only",
            label="worker_resumed_missing_only",
            writes=(
                "orchestration.worker_checkpoint",
                "orchestration.worker_health",
                "orchestration.work_item_registry",
            ),
            side_effects=("work_dispatch_write", "worker_checkpoint_write"),
            emitted_tokens=("WorkerCheckpoint", "WorkScheduled"),
            reason="restart revalidates authorization/freshness and resumes only nonterminal work",
        ),
        CaseRule(
            case_id="unchanged_rescan",
            decision="no_delta",
            label="no_delta",
            writes=("orchestration.worker_checkpoint",),
            side_effects=("worker_checkpoint_write",),
            emitted_tokens=("NoDelta", "WorkerCheckpoint"),
            reason="an unchanged inventory and policy creates no duplicate analysis or projection work",
        ),
        CaseRule(
            case_id="parent_attempts_child_write",
            decision="foreign_write_rejected",
            label="foreign_write_rejected",
            emitted_tokens=("OwnershipViolation", "M0BlockedReceipt"),
            reason="M0 coordinates pointers and work but never copies or writes a C1-C12 fact",
        ),
    ),
    hazards=(
        HazardSpec(
            failure_id="H-M0-001-incomplete-ledger-claimed-current",
            protected_error_class="object_coverage_false_complete",
            description="M0 claims current while a required object stage is missing or stale",
            protected_harm="registered user content disappears behind a complete claim",
            case_id="missing_or_stale_stage_work",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status",),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt",),
        ),
        HazardSpec(
            failure_id="H-M0-002-stale-child-accepted",
            protected_error_class="stale_child_false_green",
            description="M0 commits using a stale child receipt",
            protected_harm="parent evidence no longer describes the integrated snapshot",
            case_id="stale_child_receipt",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status",),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt",),
        ),
        HazardSpec(
            failure_id="H-M0-003-unconsumed-output-ignored",
            protected_error_class="integration_output_loss",
            description="M0 commits with an unconsumed child output",
            protected_harm="a modeled obligation silently disappears between owners",
            case_id="unconsumed_child_output",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status",),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt",),
        ),
        HazardSpec(
            failure_id="H-M0-004-parent-writes-child-state",
            protected_error_class="parent_child_ownership_violation",
            description="M0 directly writes a field owned by a child",
            protected_harm="the coordinator becomes a competing canonical authority",
            case_id="parent_attempts_child_write",
            broken_decision="child_state_written",
            broken_writes=("matter.lifecycle_axes",),
            broken_tokens=("LifecycleState",),
        ),
        HazardSpec(
            failure_id="H-M0-005-correction-keeps-stale-receipts",
            protected_error_class="correction_invalidation_failure",
            description="affected child receipts remain current after correction",
            protected_harm="withdrawn evidence still supports downstream conclusions",
            case_id="correction_invalidates_downstream",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status",),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt",),
        ),
        HazardSpec(
            failure_id="H-M0-006-partial-inventory-claimed-complete",
            protected_error_class="source_universe_false_complete",
            description="M0 commits while inventory pages or items are nonterminal",
            protected_harm="unprocessed user content is hidden",
            case_id="progressive_inventory_partial",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status", "orchestration.coverage_status"),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt", "SourceUniverseTerminal"),
        ),
        HazardSpec(
            failure_id="H-M0-007-shallow-depth-claimed-complete",
            protected_error_class="semantic_depth_false_complete",
            description="M0 commits while semantic depth work remains",
            protected_harm="missing evidence or contradictions are hidden",
            case_id="semantic_depth_partial",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status", "orchestration.depth_status"),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt", "DepthCurrent"),
        ),
        HazardSpec(
            failure_id="H-M0-008-researchguard-pending-release",
            protected_error_class="research_integration_false_release",
            description="M0 declares complete v0.1 while ResearchGuard is pending",
            protected_harm="the release claims a research capability that is unavailable",
            case_id="researchguard_pending",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status", "orchestration.research_status"),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt", "ResearchCurrent"),
        ),
        HazardSpec(
            failure_id="H-M0-009-original-owner-join-bypassed",
            protected_error_class="original_owner_join_bypass",
            description="a validated AI finding reaches C12 before its owner terminates",
            protected_harm="AI output becomes canonical through a shadow path",
            case_id="typed_finding_owner_join_pending",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status",),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("M0IntegrationReceipt",),
        ),
        HazardSpec(
            failure_id="H-M0-010-blocked-object-stops-all-progress",
            protected_error_class="global_progress_starvation",
            description="one blocked object prevents unrelated objects from advancing",
            protected_harm="the first run never converges despite independent work",
            case_id="one_object_blocked_others_progress",
            broken_decision="global_worker_blocked",
            broken_writes=("orchestration.worker_health",),
            broken_tokens=("M0BlockedReceipt",),
        ),
        HazardSpec(
            failure_id="H-M0-011-restart-duplicates-work",
            protected_error_class="worker_restart_duplication",
            description="restart redispatches terminal work and duplicates state",
            protected_harm="coverage counts and Matter revisions diverge after recovery",
            case_id="restart_from_checkpoint",
            broken_decision="worker_resumed_all_work",
            broken_writes=("orchestration.work_item_registry",),
            broken_side_effects=("work_dispatch_write",),
            broken_tokens=("WorkScheduled",),
            ignore_idempotency=True,
        ),
        HazardSpec(
            failure_id="H-M0-012-no-delta-rescan-duplicates-analysis",
            protected_error_class="unchanged_rescan_duplication",
            description="unchanged rescan schedules duplicate AI or projection work",
            protected_harm="background maintenance creates duplicate findings and unstable cards",
            case_id="unchanged_rescan",
            broken_decision="work_scheduled",
            broken_writes=("orchestration.work_item_registry",),
            broken_side_effects=("work_dispatch_write",),
            broken_tokens=("WorkScheduled",),
        ),
        HazardSpec(
            failure_id="H-M0-013-ui-ready-gap-claimed-complete",
            protected_error_class="ui_reachability_false_complete",
            description="an admitted Matter without visual, localization, or openable UI is counted complete",
            protected_harm="modeled content exists but cannot be reviewed by its first user",
            case_id="visual_localization_or_ui_gap",
            broken_decision="end_to_end_current",
            broken_writes=("orchestration.integration_status",),
            broken_side_effects=("orchestration_receipt_write",),
            broken_tokens=("AllAdmittedMattersUIReady",),
        ),
    ),
    risk_classes=(
        "state_transition",
        "ownership",
        "freshness",
        "integration",
        "coverage",
        "semantic_depth",
        "liveness",
        "recovery",
        "side_effect",
    ),
    template_no_match_reason=(
        "No template owns the exact C1-C12 autonomous ObjectCoverageLedger, "
        "durable worker, visual/localization/UI readiness, and current-receipt mesh."
    ),
    blindspots=(
        "portable child refinement and exact producer-consumer schemas require current ModelMesh",
        "production conformance and private first-run usefulness require runtime and TestMesh evidence",
    ),
    claim_boundary=(
        "This model establishes abstract M0 orchestration, ObjectCoverageLedger "
        "terminality, automatic owner scheduling, object-isolated blocking, restart/"
        "no-delta liveness, ResearchGuard release gating, UI readiness, output "
        "consumption, and ownership hazards. It does not prove child refinement, "
        "real provider coverage, installed desktop behavior, or private-run usefulness."
    ),
)
